#pragma once

//TODO 에러 코드 중복 사용하지 않도록 한다
enum class ERROR_CODE : unsigned short
{
	kNONE = 0,

	kUSER_MGR_INVALID_USER_INDEX = 11,
	kUSER_MGR_INVALID_USER_UNIQUEID = 12,
	kUSER_NOT_IN_ROOM = 13,

	kLOGIN_USER_ALREADY = 31,
	kLOGIN_USER_USED_ALL_OBJ = 32,
	kLOGIN_USER_INVALID_PW = 33,

	kNEW_ROOM_USED_ALL_OBJ = 41,
	kNEW_ROOM_FAIL_ENTER = 42,

	kENTER_ROOM_NOT_FINDE_USER = 51,
	kENTER_ROOM_INVALID_USER_STATUS = 52,
	kENTER_ROOM_NOT_USED_STATUS = 53,
	kENTER_ROOM_FULL_USER = 54,

	kROOM_INVALID_INDEX = 61,
	kROOM_NOT_USED = 62,
	kROOM_TOO_MANY_PACKET = 63,

	kLEAVE_ROOM_INVALID_ROOM_INDEX = 71,

	kCHAT_ROOM_INVALID_ROOM_NUMBER = 81,

};
