#pragma once

#include <cstdint>

enum class  PACKET_ID : uint16_t
{
	//SYSTEM
	kSYS_USER_CONNECT = 11,
	kSYS_USER_DISCONNECT = 12,
	kSYS_END = 30,

	//DB
	kDB_END = 199,

	//Client
	kLOGIN_REQUEST = 201,
	kLOGIN_RESPONSE = 202,

	kROOM_ENTER_REQUEST = 206,
	kROOM_ENTER_RESPONSE = 207,

	kROOM_LEAVE_REQUEST = 215,
	kROOM_LEAVE_RESPONSE = 216,

	kROOM_CHAT_REQUEST = 221,
	kROOM_CHAT_RESPONSE = 222,
	kROOM_CHAT_NOTIFY = 223,
};